package com.iunera.jsonldjava.schemaorg.metadatatypes;

import com.iunera.jsonldjava.schemaorg.associations.JsonldProperty;
import com.iunera.jsonldjava.schemaorg.associations.JsonldType;
import com.iunera.jsonldjava.schemaorg.associations.Vertex;

/**
 * A Report generated by governmental or non-governmental organization. */
@Vertex
@JsonldType("http://schema.org/Report")
public class Report extends Article {
  /**
   * The number or other unique designator assigned to a Report by the publishing organization. */
  @JsonldProperty("http://schema.org/reportNumber")
  public String reportNumber;
}
